### ISSUE TITLE
Why are PDE and non-PDE implementations different?

### ISSUE THREAD

**Issue by heyzude** [cpempire/pSVGD#1]
Hi, and thanks for sharing your code with us.

I wonder why PDE and non-PDE implementations are different.

I'm trying to use your code to optimize a high-dim vector, wrt an objective function, which is a typical Cross-Entropy loss in deep learning network (in my case, the high-dim vector itself is the deep learning network's weight). In this case, which implementation would be better for me?

Thank you very much for your help in advance.

**Comment by heyzude** [comment]
Is the difference Adaptive/non-Adaptive pSVGD?

**Comment by cpempire** [comment]
Thanks for reaching out. 

The difference is on the data type for PDE and nonPDE models. We used FEniCS for PDE solver, with the data as FEniCS vector. While for nonPDE models, we use numpy vector. If you do not use FEniCS to solve PDE models, then I suggest you to use nonPDE implementation.

Best, 
Peng

**Comment by cpempire** [comment]
The difference is on the data types. We used FEniCS to solve PDE models, with the data as FEniCS vector. While for nonPDE models, we use numpy vector. If you do not use FEniCS to solve PDE models, then I suggest you use nonPDE implementation.

**Comment by heyzude** [comment]
Thank you, I got it!
